" https://github.com/scrooloose/vimfiles/blob/master/vimrc "
set nocompatible

set showcmd
set showmode

set tabstop=4
set shiftwidth=4
set smarttab=4
set et
set ai
set cin

set listchars=tab:..
set list
set ffs=unix,dos,mac
set=utf-8,cp1251,koi8-r,ucs-2,cp886

set guioptions-=T
set guioptions-=m

set number
